### ISSUE TITLE
Smear notes

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/LowRezJam2020#11]
It's pretty easy to draw directly into a sprite (See `FlxSpriteUtil.drawRect`)

* Might be easy to just have a single sprite to house all smear pixels instead of many individual sprites
* Multiple kinds of smear
  * Grease smear always (a low-alpha grey, perhaps?)
  * Ketchup and mustard only when condiment on hotdog and rolling animation is 'condiment side down'

**Comment by Kenoshen** [comment]
Ok, so you are saying we just maintain a 64x64 transparent image that fills the screen, then draw onto it as smear happens?  I'm fine with that.

I think the grease should be more of an oily color.  Like a really pale yellow/red/brown (with alpha of course).

I like the idea of red and yellow smear only happening on the condiment-side-down event.
