### ISSUE TITLE
How to enforce getting condiments?

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/LowRezJam2020#27]
- The game would be nicer if we made people get the condiments
- Let player finish without, but encourage them to try again to get them

**Comment by Kenoshen** [comment]
We should probably also give them the SAUCY ending if they get the condiment and there is only the one type of condiment.  That, or have all levels have both condiments.

**Comment by MondayHopscotch** [comment]
Player now gets "Saucy" finish if there are any condiments in the level. They also get a `<-Sauce` button if they miss any.
