### ISSUE TITLE
Consider having mustard 'drain' on tunnel

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/LowRezJam2020#5]
It could be a nice visual touch to have the condiments deplete as they are applied to the hotdog

**Comment by Kenoshen** [comment]
I'm assuming the animation as it is just loops?  If we make it so it is a play-through-then-stop kind of animation, this should be pretty easy to do on the art side right?

**Comment by Kenoshen** [comment]
And maybe just ignore when the dog goes through the tunnel a second time.  Don't play the animation again, just leave it on the "empty" animation frame.
